"""Canonical programming-language vocabulary, generated from GitHub Linguist v9.6.0.

**GENERATED FILE — DO NOT EDIT.**  Regenerate with::

    python scripts/regen_programming_languages.py --tag v9.6.0

Source: https://raw.githubusercontent.com/github-linguist/linguist/v9.6.0/lib/linguist/languages.yml

Public symbols:

- :data:`LANGUAGE_ID_BY_ALIAS` — mapping from every lowercased Linguist language name
  and alias to its canonical language id (the lowercased Linguist language name).
"""

from collections.abc import Mapping
from typing import Final

LANGUAGE_ID_BY_ALIAS: Final[Mapping[str, str]] = {
    "1c enterprise": "1c enterprise",
    "2-dimensional array": "2-dimensional array",
    "4d": "4d",
    "abap": "abap",
    "abap cds": "abap cds",
    "abl": "openedge abl",
    "abnf": "abnf",
    "abuild": "alpine abuild",
    "acfm": "adobe font metrics",
    "ackrc": "option list",
    "aconf": "apacheconf",
    "actionscript": "actionscript",
    "actionscript 3": "actionscript",
    "actionscript3": "actionscript",
    "ad block": "adblock filter list",
    "ad block filters": "adblock filter list",
    "ada": "ada",
    "ada2005": "ada",
    "ada95": "ada",
    "adb": "adblock filter list",
    "adblock": "adblock filter list",
    "adblock filter list": "adblock filter list",
    "adobe composite font metrics": "adobe font metrics",
    "adobe font metrics": "adobe font metrics",
    "adobe multiple font metrics": "adobe font metrics",
    "advpl": "xbase",
    "afdko": "opentype feature file",
    "agda": "agda",
    "ags": "ags script",
    "ags script": "ags script",
    "ahk": "autohotkey",
    "aidl": "aidl",
    "aiken": "aiken",
    "al": "al",
    "algol": "algol",
    "alloy": "alloy",
    "alpine abuild": "alpine abuild",
    "altium": "altium designer",
    "altium designer": "altium designer",
    "amfm": "adobe font metrics",
    "ampl": "ampl",
    "amusewiki": "muse",
    "angelscript": "angelscript",
    "answer set programming": "answer set programming",
    "ant build system": "ant build system",
    "antlers": "antlers",
    "antlr": "antlr",
    "apache": "apacheconf",
    "apacheconf": "apacheconf",
    "apex": "apex",
    "api blueprint": "api blueprint",
    "apkbuild": "alpine abuild",
    "apl": "apl",
    "apollo guidance computer": "apollo guidance computer",
    "apples": "applescript",
    "applescript": "applescript",
    "arc": "arc",
    "arexx": "rexx",
    "as3": "actionscript",
    "ascii stl": "stl",
    "asciidoc": "asciidoc",
    "asl": "asl",
    "asm": "assembly",
    "asn.1": "asn.1",
    "asp": "classic asp",
    "asp.net": "asp.net",
    "aspectj": "aspectj",
    "aspx": "asp.net",
    "aspx-vb": "asp.net",
    "assembly": "assembly",
    "astro": "astro",
    "asymptote": "asymptote",
    "ats": "ats",
    "ats2": "ats",
    "au3": "autoit",
    "augeas": "augeas",
    "autoconf": "m4sugar",
    "autohotkey": "autohotkey",
    "autoit": "autoit",
    "autoit3": "autoit",
    "autoitscript": "autoit",
    "avro idl": "avro idl",
    "awk": "awk",
    "b (formal method)": "b (formal method)",
    "b3d": "blitzbasic",
    "b4x": "b4x",
    "ballerina": "ballerina",
    "baml": "baml",
    "bash": "shell",
    "bash session": "shellsession",
    "basic": "basic",
    "basic for android": "b4x",
    "bat": "batchfile",
    "batch": "batchfile",
    "batchfile": "batchfile",
    "bazel": "starlark",
    "be": "berry",
    "beef": "beef",
    "befunge": "befunge",
    "berry": "berry",
    "bh": "bluespec bh",
    "bibtex": "bibtex",
    "bibtex style": "bibtex style",
    "bicep": "bicep",
    "bikeshed": "bikeshed",
    "bison": "bison",
    "bitbake": "bitbake",
    "blade": "blade",
    "blitz3d": "blitzbasic",
    "blitzbasic": "blitzbasic",
    "blitzmax": "blitzmax",
    "blitzplus": "blitzbasic",
    "bluespec": "bluespec",
    "bluespec bh": "bluespec bh",
    "bluespec bsv": "bluespec",
    "bluespec classic": "bluespec bh",
    "bmax": "blitzmax",
    "boo": "boo",
    "boogie": "boogie",
    "bplus": "blitzbasic",
    "bqn": "bqn",
    "brainfuck": "brainfuck",
    "brighterscript": "brighterscript",
    "brightscript": "brightscript",
    "bro": "zeek",
    "browserslist": "browserslist",
    "bru": "bru",
    "bsdmake": "makefile",
    "bsv": "bluespec",
    "buildstream": "buildstream",
    "byond": "dm",
    "bzl": "starlark",
    "c": "c",
    "c#": "c#",
    "c++": "c++",
    "c++-objdump": "cpp-objdump",
    "c-objdump": "c-objdump",
    "c2hs": "c2hs haskell",
    "c2hs haskell": "c2hs haskell",
    "c3": "c3",
    "cabal": "cabal config",
    "cabal config": "cabal config",
    "caddy": "caddyfile",
    "caddyfile": "caddyfile",
    "cadence": "cadence",
    "cairo": "cairo",
    "cairo zero": "cairo zero",
    "cake": "c#",
    "cakescript": "c#",
    "cameligo": "cameligo",
    "cangjie": "cangjie",
    "cap cds": "cap cds",
    "cap'n proto": "cap'n proto",
    "carbon": "carbon",
    "carto": "cartocss",
    "cartocss": "cartocss",
    "cask": "emacs lisp",
    "cds": "cap cds",
    "ceylon": "ceylon",
    "cfc": "coldfusion cfc",
    "cfm": "coldfusion",
    "cfml": "coldfusion",
    "chapel": "chapel",
    "charity": "charity",
    "checksum": "checksums",
    "checksums": "checksums",
    "chpl": "chapel",
    "chuck": "chuck",
    "cil": "cil",
    "circom": "circom",
    "cirru": "cirru",
    "clarion": "clarion",
    "clarity": "clarity",
    "classic asp": "classic asp",
    "classic qbasic": "quickbasic",
    "classic quickbasic": "quickbasic",
    "classic visual basic": "visual basic 6.0",
    "clean": "clean",
    "click": "click",
    "clipper": "xbase",
    "clips": "clips",
    "clojure": "clojure",
    "closure templates": "closure templates",
    "cloud firestore security rules": "cloud firestore security rules",
    "clue": "clue",
    "cmake": "cmake",
    "cobol": "cobol",
    "coccinelle": "smpl",
    "codeowners": "codeowners",
    "codeql": "codeql",
    "coffee": "coffeescript",
    "coffee-script": "coffeescript",
    "coffeescript": "coffeescript",
    "coldfusion": "coldfusion",
    "coldfusion cfc": "coldfusion cfc",
    "coldfusion html": "coldfusion",
    "collada": "collada",
    "commit": "git commit",
    "common lisp": "common lisp",
    "common workflow language": "common workflow language",
    "component pascal": "component pascal",
    "conf": "ini",
    "conll": "conll-u",
    "conll-u": "conll-u",
    "conll-x": "conll-u",
    "console": "shellsession",
    "containerfile": "dockerfile",
    "cooklang": "cooklang",
    "cool": "cool",
    "coq": "rocq prover",
    "cperl": "perl",
    "cpp": "c++",
    "cpp-objdump": "cpp-objdump",
    "cql": "cql",
    "creole": "creole",
    "cron": "crontab",
    "cron table": "crontab",
    "crontab": "crontab",
    "crystal": "crystal",
    "csharp": "c#",
    "cson": "cson",
    "csound": "csound",
    "csound document": "csound document",
    "csound score": "csound score",
    "csound-csd": "csound document",
    "csound-orc": "csound",
    "csound-sco": "csound score",
    "css": "css",
    "csv": "csv",
    "cucumber": "gherkin",
    "cuda": "cuda",
    "cue": "cue",
    "cue sheet": "cue sheet",
    "curl config": "curl config",
    "curlrc": "curl config",
    "curry": "curry",
    "cweb": "cweb",
    "cwl": "common workflow language",
    "cycript": "cycript",
    "cylc": "cylc",
    "cypher": "cypher",
    "cython": "cython",
    "d": "d",
    "d-objdump": "d-objdump",
    "d2": "d2",
    "d2lang": "d2",
    "dafny": "dafny",
    "darcs patch": "darcs patch",
    "dart": "dart",
    "daslang": "daslang",
    "dataweave": "dataweave",
    "dcl": "digital command language",
    "debian package control file": "debian package control file",
    "delphi": "pascal",
    "denizenscript": "denizenscript",
    "desktop": "desktop",
    "dhall": "dhall",
    "diff": "diff",
    "digital command language": "digital command language",
    "dircolors": "dircolors",
    "directx 3d file": "directx 3d file",
    "django": "jinja",
    "dlang": "d",
    "dm": "dm",
    "dns zone": "dns zone",
    "dockerfile": "dockerfile",
    "dogescript": "dogescript",
    "dosbatch": "batchfile",
    "dosini": "ini",
    "dotenv": "dotenv",
    "dpatch": "darcs patch",
    "dtrace": "dtrace",
    "dtrace-script": "dtrace",
    "dune": "dune",
    "dylan": "dylan",
    "e": "e",
    "e-mail": "e-mail",
    "eagle": "eagle",
    "earthfile": "earthly",
    "earthly": "earthly",
    "eask": "emacs lisp",
    "easybuild": "easybuild",
    "ebnf": "ebnf",
    "ec": "ec",
    "ecere projects": "ecere projects",
    "ecl": "ecl",
    "eclipse": "eclipse",
    "ecmarkdown": "ecmarkup",
    "ecmarkup": "ecmarkup",
    "ecr": "html+ecr",
    "edge": "edge",
    "edgeql": "edgeql",
    "editor-config": "editorconfig",
    "editorconfig": "editorconfig",
    "edje data collection": "edje data collection",
    "edn": "edn",
    "eeschema schematic": "kicad schematic",
    "eex": "html+eex",
    "eiffel": "eiffel",
    "ejs": "ejs",
    "electronic business card": "vcard",
    "elisp": "emacs lisp",
    "elixir": "elixir",
    "elm": "elm",
    "elvish": "elvish",
    "elvish transcript": "elvish transcript",
    "emacs": "emacs lisp",
    "emacs lisp": "emacs lisp",
    "emacs muse": "muse",
    "email": "e-mail",
    "emberscript": "emberscript",
    "eml": "e-mail",
    "envrc": "shell",
    "eq": "eq",
    "erb": "html+erb",
    "erlang": "erlang",
    "esdl": "edgeql",
    "euphoria": "euphoria",
    "f#": "f#",
    "f*": "f*",
    "factor": "factor",
    "fancy": "fancy",
    "fantom": "fantom",
    "faust": "faust",
    "fb": "freebasic",
    "fennel": "fennel",
    "figfont": "figlet font",
    "figlet font": "figlet font",
    "filebench wml": "filebench wml",
    "filterscript": "filterscript",
    "firrtl": "firrtl",
    "fish": "fish",
    "flatbuffers": "flatbuffers",
    "flex": "lex",
    "flix": "flix",
    "fluent": "fluent",
    "flux": "flux",
    "formatted": "formatted",
    "forth": "forth",
    "fortran": "fortran",
    "fortran free form": "fortran free form",
    "foxpro": "xbase",
    "freebasic": "freebasic",
    "freemarker": "freemarker",
    "frege": "frege",
    "fsharp": "f#",
    "fstar": "f*",
    "ftl": "freemarker",
    "fundamental": "text",
    "futhark": "futhark",
    "g-code": "g-code",
    "game maker language": "game maker language",
    "gaml": "gaml",
    "gams": "gams",
    "gap": "gap",
    "gas": "unix assembly",
    "gcc machine description": "gcc machine description",
    "gdb": "gdb",
    "gdscript": "gdscript",
    "gdshader": "gdshader",
    "gedcom": "gedcom",
    "gemfile.lock": "gemfile.lock",
    "gemini": "gemini",
    "gemtext": "gemini",
    "genero 4gl": "genero 4gl",
    "genero per": "genero per",
    "genie": "genie",
    "genshi": "genshi",
    "gentoo ebuild": "gentoo ebuild",
    "gentoo eclass": "gentoo eclass",
    "geojson": "json",
    "gerber image": "gerber image",
    "gettext catalog": "gettext catalog",
    "gf": "grammatical framework",
    "gherkin": "gherkin",
    "git attributes": "git attributes",
    "git blame ignore revs": "git revision list",
    "git commit": "git commit",
    "git config": "git config",
    "git revision list": "git revision list",
    "git-ignore": "ignore list",
    "gitattributes": "git attributes",
    "gitconfig": "git config",
    "gitignore": "ignore list",
    "gitmodules": "git config",
    "gjs": "glimmer js",
    "gleam": "gleam",
    "glimmer js": "glimmer js",
    "glimmer ts": "glimmer ts",
    "glsl": "glsl",
    "glyph": "glyph",
    "glyph bitmap distribution format": "glyph bitmap distribution format",
    "gn": "gn",
    "gnu asm": "unix assembly",
    "gnuplot": "gnuplot",
    "go": "go",
    "go checksums": "go checksums",
    "go mod": "go module",
    "go module": "go module",
    "go sum": "go checksums",
    "go template": "go template",
    "go work": "go workspace",
    "go work sum": "go checksums",
    "go workspace": "go workspace",
    "go.mod": "go module",
    "go.sum": "go checksums",
    "go.work": "go workspace",
    "go.work.sum": "go checksums",
    "godot resource": "godot resource",
    "golang": "go",
    "golo": "golo",
    "gosu": "gosu",
    "gotmpl": "go template",
    "grace": "grace",
    "gradle": "gradle",
    "gradle kotlin dsl": "gradle kotlin dsl",
    "grammatical framework": "grammatical framework",
    "graph modeling language": "graph modeling language",
    "graphql": "graphql",
    "graphviz (dot)": "graphviz (dot)",
    "groff": "roff",
    "groovy": "groovy",
    "groovy server pages": "groovy server pages",
    "gsc": "gsc",
    "gsp": "groovy server pages",
    "gtk": "gtkrc",
    "gtk 1": "gtkrc",
    "gtk 2": "gtkrc",
    "gtkrc": "gtkrc",
    "gts": "glimmer ts",
    "hack": "hack",
    "haml": "haml",
    "handlebars": "handlebars",
    "haproxy": "haproxy",
    "harbour": "harbour",
    "hare": "hare",
    "hash": "checksums",
    "hashes": "checksums",
    "hashicorp configuration language": "hcl",
    "haskell": "haskell",
    "haxe": "haxe",
    "hbs": "handlebars",
    "hcl": "hcl",
    "heex": "html+eex",
    "help": "vim help file",
    "hip": "hip",
    "hiveql": "hiveql",
    "hls playlist": "m3u",
    "hlsl": "hlsl",
    "hocon": "hocon",
    "holyc": "holyc",
    "hoon": "hoon",
    "hosts": "hosts file",
    "hosts file": "hosts file",
    "html": "html",
    "html+django": "jinja",
    "html+ecr": "html+ecr",
    "html+eex": "html+eex",
    "html+erb": "html+erb",
    "html+jinja": "jinja",
    "html+php": "html+php",
    "html+razor": "html+razor",
    "html+ruby": "html+erb",
    "htmlbars": "handlebars",
    "htmldjango": "jinja",
    "http": "http",
    "hurl": "hurl",
    "hxml": "hxml",
    "hy": "hy",
    "hylang": "hy",
    "hyphy": "hyphy",
    "i7": "inform 7",
    "ical": "icalendar",
    "icalendar": "icalendar",
    "idl": "idl",
    "idris": "idris",
    "ignore": "ignore list",
    "ignore list": "ignore list",
    "igor": "igor pro",
    "igor pro": "igor pro",
    "igorpro": "igor pro",
    "ijm": "imagej macro",
    "il assembly": "il assembly",
    "ilasm": "il assembly",
    "ile rpg": "rpgle",
    "imagej macro": "imagej macro",
    "imba": "imba",
    "inc": "php",
    "inform 7": "inform 7",
    "inform7": "inform 7",
    "ini": "ini",
    "ink": "ink",
    "inno setup": "inno setup",
    "inputrc": "readline config",
    "io": "io",
    "ioke": "ioke",
    "ipython notebook": "jupyter notebook",
    "irc": "irc log",
    "irc log": "irc log",
    "irc logs": "irc log",
    "isabelle": "isabelle",
    "isabelle root": "isabelle root",
    "ispc": "ispc",
    "j": "j",
    "jac": "jac",
    "jai": "jai",
    "janet": "janet",
    "jar manifest": "jar manifest",
    "jasmin": "jasmin",
    "java": "java",
    "java properties": "java properties",
    "java server page": "groovy server pages",
    "java server pages": "java server pages",
    "java template engine": "java template engine",
    "javascript": "javascript",
    "javascript+erb": "javascript+erb",
    "jcl": "jcl",
    "jest snapshot": "jest snapshot",
    "jetbrains mps": "jetbrains mps",
    "jflex": "jflex",
    "jinja": "jinja",
    "jison": "jison",
    "jison lex": "jison lex",
    "jolie": "jolie",
    "jq": "jq",
    "jruby": "ruby",
    "js": "javascript",
    "json": "json",
    "json with comments": "json with comments",
    "json5": "json5",
    "jsonc": "json with comments",
    "jsoniq": "jsoniq",
    "jsonl": "json",
    "jsonld": "jsonld",
    "jsonnet": "jsonnet",
    "jsp": "java server pages",
    "jte": "java template engine",
    "julia": "julia",
    "julia repl": "julia repl",
    "jupyter notebook": "jupyter notebook",
    "just": "just",
    "justfile": "just",
    "kaitai struct": "kaitai struct",
    "kak": "kakounescript",
    "kakounescript": "kakounescript",
    "kakscript": "kakounescript",
    "kcl": "kcl",
    "kdl": "kdl",
    "kerboscript": "kerboscript",
    "keyvalues": "valve data format",
    "kframework": "kframework",
    "kicad layout": "kicad layout",
    "kicad legacy layout": "kicad legacy layout",
    "kicad schematic": "kicad schematic",
    "kickstart": "kickstart",
    "kit": "kit",
    "koka": "koka",
    "kolmafia ash": "kolmafia ash",
    "kotlin": "kotlin",
    "krl": "krl",
    "ksy": "kaitai struct",
    "kusto": "kusto",
    "kvlang": "kvlang",
    "labview": "labview",
    "lambdapi": "lambdapi",
    "langium": "langium",
    "lark": "lark",
    "lasso": "lasso",
    "lassoscript": "lasso",
    "latex": "tex",
    "latte": "latte",
    "lean": "lean",
    "lean 4": "lean 4",
    "lean4": "lean 4",
    "leex": "html+eex",
    "leo": "leo",
    "less": "less",
    "less-css": "less",
    "lex": "lex",
    "lfe": "lfe",
    "lhaskell": "literate haskell",
    "lhs": "literate haskell",
    "ligolang": "ligolang",
    "lilypond": "lilypond",
    "limbo": "limbo",
    "linear programming": "linear programming",
    "linker script": "linker script",
    "linux kernel module": "linux kernel module",
    "liquid": "liquid",
    "liquidsoap": "liquidsoap",
    "lisp": "common lisp",
    "litcoffee": "literate coffeescript",
    "literate agda": "literate agda",
    "literate coffeescript": "literate coffeescript",
    "literate haskell": "literate haskell",
    "live-script": "livescript",
    "livecode script": "livecode script",
    "livescript": "livescript",
    "llvm": "llvm",
    "logos": "logos",
    "logtalk": "logtalk",
    "lolcode": "lolcode",
    "lookml": "lookml",
    "loomscript": "loomscript",
    "ls": "livescript",
    "lsl": "lsl",
    "ltspice symbol": "ltspice symbol",
    "lua": "lua",
    "luau": "luau",
    "m": "m",
    "m2": "macaulay2",
    "m3u": "m3u",
    "m3u playlist": "m3u",
    "m4": "m4",
    "m4sugar": "m4sugar",
    "m68k": "motorola 68k assembly",
    "macaulay2": "macaulay2",
    "macruby": "ruby",
    "mail": "e-mail",
    "make": "makefile",
    "makefile": "makefile",
    "mako": "mako",
    "man": "roff",
    "man page": "roff",
    "man-page": "roff",
    "manpage": "roff",
    "markdown": "markdown",
    "marko": "marko",
    "markojs": "marko",
    "mask": "mask",
    "mathematica": "wolfram language",
    "mathematical programming system": "mathematical programming system",
    "matlab": "matlab",
    "maven pom": "maven pom",
    "max": "max",
    "max/msp": "max",
    "maxmsp": "max",
    "maxscript": "maxscript",
    "mbox": "e-mail",
    "mcfunction": "mcfunction",
    "md": "markdown",
    "mdoc": "roff",
    "mdsvex": "mdsvex",
    "mdx": "mdx",
    "mediawiki": "wikitext",
    "mercury": "mercury",
    "mermaid": "mermaid",
    "mermaid example": "mermaid",
    "meson": "meson",
    "metal": "metal",
    "metta": "metta",
    "mf": "makefile",
    "microsoft developer studio project": "microsoft developer studio project",
    "microsoft visual studio solution": "microsoft visual studio solution",
    "minid": "minid",
    "miniyaml": "miniyaml",
    "minizinc": "minizinc",
    "minizinc data": "minizinc data",
    "mint": "mint",
    "mirah": "mirah",
    "mirc script": "mirc script",
    "mlir": "mlir",
    "mma": "wolfram language",
    "modelica": "modelica",
    "modula-2": "modula-2",
    "modula-3": "modula-3",
    "module management system": "module management system",
    "mojo": "mojo",
    "monkey": "monkey",
    "monkey c": "monkey c",
    "moocode": "moocode",
    "moonbit": "moonbit",
    "moonscript": "moonscript",
    "motoko": "motoko",
    "motorola 68k assembly": "motorola 68k assembly",
    "move": "move",
    "mps": "jetbrains mps",
    "mql4": "mql4",
    "mql5": "mql5",
    "msil": "il assembly",
    "mtml": "mtml",
    "muf": "muf",
    "mumps": "m",
    "mupad": "mupad",
    "muse": "muse",
    "mustache": "mustache",
    "myghty": "myghty",
    "nanorc": "nanorc",
    "nargo": "noir",
    "nasal": "nasal",
    "nasl": "nasl",
    "nasm": "assembly",
    "ncl": "ncl",
    "ne-on": "neon",
    "nearley": "nearley",
    "nemerle": "nemerle",
    "neon": "neon",
    "neosnippet": "vim snippet",
    "nesc": "nesc",
    "netlinx": "netlinx",
    "netlinx+erb": "netlinx+erb",
    "netlogo": "netlogo",
    "nette object notation": "neon",
    "newlisp": "newlisp",
    "nextflow": "nextflow",
    "nginx": "nginx",
    "nginx configuration file": "nginx",
    "nickel": "nickel",
    "nim": "nim",
    "ninja": "ninja",
    "nit": "nit",
    "nix": "nix",
    "nixos": "nix",
    "njk": "nunjucks",
    "nl": "nl",
    "nmodl": "nmodl",
    "node": "javascript",
    "noir": "noir",
    "npm config": "npm config",
    "npmrc": "npm config",
    "nroff": "roff",
    "nsis": "nsis",
    "nu": "nu",
    "nu-script": "nushell",
    "numpy": "numpy",
    "nunjucks": "nunjucks",
    "nush": "nu",
    "nushell": "nushell",
    "nushell-script": "nushell",
    "nvim": "vim script",
    "nwscript": "nwscript",
    "oasv2": "openapi specification v2",
    "oasv2-json": "oasv2-json",
    "oasv2-yaml": "oasv2-yaml",
    "oasv3": "openapi specification v3",
    "oasv3-json": "oasv3-json",
    "oasv3-yaml": "oasv3-yaml",
    "oberon": "oberon",
    "obj-c": "objective-c",
    "obj-c++": "objective-c++",
    "obj-j": "objective-j",
    "objc": "objective-c",
    "objc++": "objective-c++",
    "objdump": "objdump",
    "object data instance notation": "object data instance notation",
    "objective-c": "objective-c",
    "objective-c++": "objective-c++",
    "objective-j": "objective-j",
    "objectivec": "objective-c",
    "objectivec++": "objective-c++",
    "objectivej": "objective-j",
    "objectpascal": "pascal",
    "objectscript": "objectscript",
    "objj": "objective-j",
    "ocaml": "ocaml",
    "octave": "matlab",
    "odin": "odin",
    "odin-lang": "odin",
    "odinlang": "odin",
    "omgrofl": "omgrofl",
    "omnet++ msg": "omnet++ msg",
    "omnet++ ned": "omnet++ ned",
    "omnetpp-msg": "omnet++ msg",
    "omnetpp-ned": "omnet++ ned",
    "oncrpc": "rpc",
    "ooc": "ooc",
    "opa": "opa",
    "opal": "opal",
    "open policy agent": "open policy agent",
    "openapi specification v2": "openapi specification v2",
    "openapi specification v3": "openapi specification v3",
    "opencl": "opencl",
    "openedge": "openedge abl",
    "openedge abl": "openedge abl",
    "openqasm": "openqasm",
    "openrc": "openrc runscript",
    "openrc runscript": "openrc runscript",
    "openscad": "openscad",
    "openstep property list": "openstep property list",
    "opentofu": "hcl",
    "opentype feature file": "opentype feature file",
    "option list": "option list",
    "opts": "option list",
    "opy": "overpy",
    "org": "org",
    "osascript": "applescript",
    "overpassql": "overpassql",
    "overpy": "overpy",
    "ox": "ox",
    "oxygene": "oxygene",
    "oz": "oz",
    "p4": "p4",
    "pact": "pact",
    "pan": "pan",
    "pandoc": "markdown",
    "papyrus": "papyrus",
    "parrot": "parrot",
    "parrot assembly": "parrot assembly",
    "parrot internal representation": "parrot internal representation",
    "pascal": "pascal",
    "pasm": "parrot assembly",
    "pawn": "pawn",
    "pcbnew": "kicad layout",
    "pddl": "pddl",
    "peg.js": "peg.js",
    "pep8": "pep8",
    "perl": "perl",
    "perl-6": "raku",
    "perl6": "raku",
    "php": "php",
    "pic": "pic",
    "pickle": "pickle",
    "picolisp": "picolisp",
    "piglatin": "piglatin",
    "pikchr": "pic",
    "pike": "pike",
    "pip requirements": "pip requirements",
    "pir": "parrot internal representation",
    "pkg-config": "pkg-config",
    "pkgconf": "pkg-config",
    "pkl": "pkl",
    "plain text": "text",
    "plantuml": "plantuml",
    "plpgsql": "plpgsql",
    "plsql": "plsql",
    "pod": "pod",
    "pod 6": "pod 6",
    "pogoscript": "pogoscript",
    "polar": "polar",
    "pony": "pony",
    "portugol": "portugol",
    "posh": "powershell",
    "postcss": "postcss",
    "postscr": "postscript",
    "postscript": "postscript",
    "pot": "gettext catalog",
    "pov-ray": "pov-ray sdl",
    "pov-ray sdl": "pov-ray sdl",
    "povray": "pov-ray sdl",
    "power query": "power query",
    "powerbuilder": "powerbuilder",
    "powerquery": "power query",
    "powershell": "powershell",
    "praat": "praat",
    "prisma": "prisma",
    "pro*c": "pro*c",
    "processing": "processing",
    "procfile": "procfile",
    "progress": "openedge abl",
    "proguard": "proguard",
    "prolog": "prolog",
    "promela": "promela",
    "propeller spin": "propeller spin",
    "proto": "protocol buffer",
    "protobuf": "protocol buffer",
    "protobuf text format": "protocol buffer text format",
    "protocol buffer": "protocol buffer",
    "protocol buffer text format": "protocol buffer text format",
    "protocol buffers": "protocol buffer",
    "public key": "public key",
    "pug": "pug",
    "puppet": "puppet",
    "pure data": "pure data",
    "purebasic": "purebasic",
    "purescript": "purescript",
    "pwsh": "powershell",
    "py": "python",
    "py3": "python",
    "pycon": "python console",
    "pyret": "pyret",
    "pyrex": "cython",
    "python": "python",
    "python console": "python console",
    "python traceback": "python traceback",
    "python3": "python",
    "q": "q",
    "q#": "q#",
    "qb": "quickbasic",
    "qb64": "quickbasic",
    "qbasic": "quickbasic",
    "ql": "codeql",
    "qmake": "qmake",
    "qml": "qml",
    "qsharp": "q#",
    "qt script": "qt script",
    "quake": "quake",
    "quakec": "quakec",
    "quickbasic": "quickbasic",
    "quint": "quint",
    "r": "r",
    "racket": "racket",
    "ragel": "ragel",
    "ragel-rb": "ragel",
    "ragel-ruby": "ragel",
    "rake": "ruby",
    "raku": "raku",
    "raml": "raml",
    "rascal": "rascal",
    "rascript": "rascript",
    "raw": "raw token data",
    "raw token data": "raw token data",
    "razor": "html+razor",
    "rb": "ruby",
    "rbs": "rbs",
    "rbx": "ruby",
    "rdoc": "rdoc",
    "readline": "readline config",
    "readline config": "readline config",
    "realbasic": "realbasic",
    "reason": "reason",
    "reasonligo": "reasonligo",
    "rebol": "rebol",
    "record jar": "record jar",
    "red": "red",
    "red/system": "red",
    "redcode": "redcode",
    "redirect rules": "redirect rules",
    "redirects": "redirect rules",
    "redscript": "redscript",
    "regex": "regular expression",
    "regexp": "regular expression",
    "regular expression": "regular expression",
    "ren'py": "ren'py",
    "renderscript": "renderscript",
    "renpy": "ren'py",
    "rescript": "rescript",
    "restructuredtext": "restructuredtext",
    "rexx": "rexx",
    "rez": "rez",
    "rhtml": "html+erb",
    "rich text format": "rich text format",
    "ring": "ring",
    "riot": "riot",
    "rmarkdown": "rmarkdown",
    "robotframework": "robotframework",
    "robots": "robots exclusion rules",
    "robots exclusion rules": "robots exclusion rules",
    "robots txt": "robots exclusion rules",
    "robotx.txt": "robots exclusion rules",
    "roc": "roc",
    "rocq": "rocq prover",
    "rocq prover": "rocq prover",
    "roff": "roff",
    "roff manpage": "roff manpage",
    "ron": "ron",
    "ros interface": "ros interface",
    "rosmsg": "ros interface",
    "rouge": "rouge",
    "routeros script": "routeros script",
    "rpc": "rpc",
    "rpcgen": "rpc",
    "rpgle": "rpgle",
    "rpm spec": "rpm spec",
    "rs": "rust",
    "rs-274x": "gerber image",
    "rscript": "r",
    "rss": "xml",
    "rst": "restructuredtext",
    "ruby": "ruby",
    "runoff": "runoff",
    "rust": "rust",
    "rusthon": "python",
    "sage": "sage",
    "sail": "sail",
    "salt": "saltstack",
    "saltstack": "saltstack",
    "saltstate": "saltstack",
    "sarif": "json",
    "sas": "sas",
    "sass": "sass",
    "scala": "scala",
    "scaml": "scaml",
    "scenic": "scenic",
    "scheme": "scheme",
    "scilab": "scilab",
    "scss": "scss",
    "sdc": "tcl",
    "sed": "sed",
    "self": "self",
    "selinux kernel policy language": "selinux policy",
    "selinux policy": "selinux policy",
    "sepolicy": "selinux policy",
    "sfv": "simple file verification",
    "sh": "shell",
    "shaderlab": "shaderlab",
    "shell": "shell",
    "shell-script": "shell",
    "shellcheck config": "shellcheck config",
    "shellcheckrc": "shellcheck config",
    "shellsession": "shellsession",
    "shen": "shen",
    "sieve": "sieve",
    "simple file verification": "simple file verification",
    "singularity": "singularity",
    "slang": "slang",
    "slash": "slash",
    "slice": "slice",
    "slim": "slim",
    "slint": "slint",
    "smali": "smali",
    "smalltalk": "smalltalk",
    "smarty": "smarty",
    "smithy": "smithy",
    "sml": "standard ml",
    "smpl": "smpl",
    "smt": "smt",
    "snakefile": "snakemake",
    "snakemake": "snakemake",
    "snipmate": "vim snippet",
    "snippet": "yasnippet",
    "solidity": "solidity",
    "soong": "soong",
    "sourcemod": "sourcepawn",
    "sourcepawn": "sourcepawn",
    "soy": "closure templates",
    "sparql": "sparql",
    "specfile": "rpm spec",
    "spicedb schema": "spicedb schema",
    "spline font database": "spline font database",
    "splus": "r",
    "sqf": "sqf",
    "sql": "sql",
    "sqlpl": "sqlpl",
    "sqlrpgle": "rpgle",
    "squeak": "smalltalk",
    "squirrel": "squirrel",
    "srecode template": "srecode template",
    "ssh config": "ssh config",
    "ssh_config": "ssh config",
    "sshconfig": "ssh config",
    "sshd_config": "ssh config",
    "sshdconfig": "ssh config",
    "stan": "stan",
    "standard ml": "standard ml",
    "star": "star",
    "starlark": "starlark",
    "stata": "stata",
    "stl": "stl",
    "stla": "stl",
    "ston": "ston",
    "stringtemplate": "stringtemplate",
    "stylus": "stylus",
    "subrip text": "subrip text",
    "sugarss": "sugarss",
    "sum": "checksums",
    "sums": "checksums",
    "supercollider": "supercollider",
    "surql": "surrealql",
    "surrealql": "surrealql",
    "survex data": "survex data",
    "svelte": "svelte",
    "svg": "svg",
    "sway": "sway",
    "sweave": "sweave",
    "swift": "swift",
    "swig": "swig",
    "systemverilog": "systemverilog",
    "tab-seperated values": "tsv",
    "tabular model definition language": "tmdl",
    "tact": "tact",
    "talon": "talon",
    "tcl": "tcl",
    "tcsh": "tcsh",
    "tea": "tea",
    "teal": "teal",
    "templ": "templ",
    "terra": "terra",
    "terraform": "hcl",
    "terraform template": "terraform template",
    "tex": "tex",
    "texinfo": "texinfo",
    "text": "text",
    "text proto": "protocol buffer text format",
    "textgrid": "textgrid",
    "textile": "textile",
    "textmate properties": "textmate properties",
    "thrift": "thrift",
    "ti program": "ti program",
    "tl": "type language",
    "tl-verilog": "tl-verilog",
    "tla": "tla",
    "tm-properties": "textmate properties",
    "tmdl": "tmdl",
    "toit": "toit",
    "toml": "toml",
    "topojson": "json",
    "tor config": "tor config",
    "torrc": "tor config",
    "traveling salesman problem": "tsplib data",
    "travelling salesman problem": "tsplib data",
    "tree-sitter query": "tree-sitter query",
    "troff": "roff",
    "ts": "typescript",
    "tsp": "typespec",
    "tsplib data": "tsplib data",
    "tsq": "tree-sitter query",
    "tsql": "tsql",
    "tsv": "tsv",
    "tsx": "tsx",
    "turing": "turing",
    "turtle": "turtle",
    "twig": "twig",
    "txl": "txl",
    "typ": "typst",
    "type language": "type language",
    "typescript": "typescript",
    "typescriptreact": "tsx",
    "typespec": "typespec",
    "typst": "typst",
    "udiff": "diff",
    "ultisnip": "vim snippet",
    "ultisnips": "vim snippet",
    "unified parallel c": "unified parallel c",
    "unity3d asset": "unity3d asset",
    "unix asm": "unix assembly",
    "unix assembly": "unix assembly",
    "uno": "uno",
    "unrealscript": "unrealscript",
    "untyped plutus core": "untyped plutus core",
    "ur": "urweb",
    "ur/web": "urweb",
    "urweb": "urweb",
    "v": "v",
    "vala": "vala",
    "valve data format": "valve data format",
    "vb .net": "visual basic .net",
    "vb 6": "visual basic 6.0",
    "vb.net": "visual basic .net",
    "vb6": "visual basic 6.0",
    "vba": "vba",
    "vbnet": "visual basic .net",
    "vbscript": "vbscript",
    "vcard": "vcard",
    "vcl": "vcl",
    "vdf": "valve data format",
    "velocity": "velocity template language",
    "velocity template language": "velocity template language",
    "vento": "vento",
    "verilog": "verilog",
    "vhdl": "vhdl",
    "vim": "vim script",
    "vim help file": "vim help file",
    "vim script": "vim script",
    "vim snippet": "vim snippet",
    "vimhelp": "vim help file",
    "viml": "vim script",
    "vimscript": "vim script",
    "virtual contact file": "vcard",
    "visual basic": "visual basic .net",
    "visual basic .net": "visual basic .net",
    "visual basic 6": "visual basic 6.0",
    "visual basic 6.0": "visual basic 6.0",
    "visual basic classic": "visual basic 6.0",
    "visual basic for applications": "vba",
    "vlang": "v",
    "volt": "volt",
    "vtl": "velocity template language",
    "vtt": "webvtt",
    "vue": "vue",
    "vyper": "vyper",
    "wasm": "webassembly",
    "wast": "webassembly",
    "wavefront material": "wavefront material",
    "wavefront object": "wavefront object",
    "wdl": "wdl",
    "web ontology language": "web ontology language",
    "webassembly": "webassembly",
    "webassembly interface type": "webassembly interface type",
    "webidl": "webidl",
    "webvtt": "webvtt",
    "wget config": "wget config",
    "wgetrc": "wget config",
    "wgsl": "wgsl",
    "whiley": "whiley",
    "wiki": "wikitext",
    "wikitext": "wikitext",
    "win32 message file": "win32 message file",
    "winbatch": "batchfile",
    "windows registry entries": "windows registry entries",
    "wisp": "wisp",
    "wit": "webassembly interface type",
    "witcher script": "witcher script",
    "wl": "wolfram language",
    "wolfram": "wolfram language",
    "wolfram lang": "wolfram language",
    "wolfram language": "wolfram language",
    "wollok": "wollok",
    "workflow description language": "wdl",
    "world of warcraft addon data": "world of warcraft addon data",
    "wren": "wren",
    "wrenlang": "wren",
    "wsdl": "xml",
    "x bitmap": "x bitmap",
    "x font directory index": "x font directory index",
    "x pixmap": "x pixmap",
    "x10": "x10",
    "xbase": "xbase",
    "xbm": "x bitmap",
    "xc": "xc",
    "xcompose": "xcompose",
    "xdc": "tcl",
    "xdr": "rpc",
    "xhtml": "html",
    "xmake": "xmake",
    "xml": "xml",
    "xml property list": "xml property list",
    "xml+genshi": "genshi",
    "xml+kid": "genshi",
    "xojo": "xojo",
    "xonsh": "xonsh",
    "xpages": "xpages",
    "xpm": "x pixmap",
    "xproc": "xproc",
    "xquery": "xquery",
    "xs": "xs",
    "xsd": "xml",
    "xsl": "xslt",
    "xslt": "xslt",
    "xten": "x10",
    "xtend": "xtend",
    "yacc": "yacc",
    "yaml": "yaml",
    "yang": "yang",
    "yara": "yara",
    "yas": "yasnippet",
    "yasnippet": "yasnippet",
    "yml": "yaml",
    "yul": "yul",
    "zap": "zap",
    "zeek": "zeek",
    "zenscript": "zenscript",
    "zephir": "zephir",
    "zig": "zig",
    "zil": "zil",
    "zimpl": "zimpl",
    "zmodel": "zmodel",
    "zsh": "shell",
}
"""Maps every lowercased Linguist language name and alias to its canonical language id."""
