"""Canonical programming-language vocabulary and its lookup/validation operations.

The vocabulary is the language registry of `GitHub Linguist
<https://github.com/github-linguist/linguist>`_ (``lib/linguist/languages.yml``), vendored
as a generated module at a pinned release (see
:mod:`~guffin.common.programming_language_data`, regenerated by
``scripts/regen_programming_languages.py``).  A **canonical language id** is the
lowercased Linguist language name (``python``, ``fortran``, ``c++``, ``text``); every
Linguist name and alias, lowercased, resolves to one.

Public symbols:

- :data:`CANONICAL_LANGUAGE_IDS` — the set of canonical language ids.
- :data:`CodeLanguageId` — a validated canonical language id string; Pydantic enforces
  membership wherever the annotation appears.
- :func:`canonical_language_id` — resolve a language name or alias (case-insensitive) to
  its canonical id, or ``None`` when the vocabulary has no such language.
- :func:`verified_code_language_id` — return a string after verifying it is a canonical
  language id.
"""

from typing import Annotated, Final

from pydantic import AfterValidator, validate_call

from guffin.common.programming_language_data import LANGUAGE_ID_BY_ALIAS

CANONICAL_LANGUAGE_IDS: Final[frozenset[str]] = frozenset(LANGUAGE_ID_BY_ALIAS.values())
"""The canonical language ids: every lowercased Linguist language name."""


def _checked_code_language_id(language_id: str) -> str:
    """Validate that *language_id* is a canonical language id; return it unchanged.

    Args:
        language_id: The candidate language id.

    Returns:
        *language_id*, when it is a canonical language id.

    Raises:
        ValueError: If *language_id* is not a canonical language id (an alias or a
            differently-cased name is rejected too: the id form is exact).
    """
    if language_id not in CANONICAL_LANGUAGE_IDS:
        raise ValueError(f"{language_id!r} is not a canonical language id")
    return language_id


type CodeLanguageId = Annotated[str, AfterValidator(_checked_code_language_id)]
"""A validated canonical language id: a lowercased Linguist language name.

The annotation carries the membership check, so Pydantic enforces it wherever the type
appears (model fields, ``@validate_call`` parameters): a value typed ``CodeLanguageId``
*is* a canonical language id, not merely a string that claims to be one.  To resolve a
free-form name or alias into an id, use :func:`canonical_language_id`; to validate an id
imperatively, use :func:`verified_code_language_id`.
"""


@validate_call
def canonical_language_id(language_text: str) -> str | None:
    """Resolve a language name or alias to its canonical language id, or ``None``.

    Matching is case-insensitive over the vocabulary's language names and aliases, with
    surrounding whitespace ignored (``FORTRAN`` → ``fortran``, ``GNU asm`` →
    ``unix assembly``, ``plain text`` → ``text``).

    Args:
        language_text: A language name or alias, in any case.

    Returns:
        The canonical language id, or ``None`` when the vocabulary has no language by
        that name or alias.
    """
    return LANGUAGE_ID_BY_ALIAS.get(language_text.strip().lower())


@validate_call
def verified_code_language_id(language_id: str) -> CodeLanguageId:
    """Return *language_id* after verifying it is a canonical language id.

    The imperative form of :data:`CodeLanguageId`: applies the same membership check the
    annotation carries.  The id form is exact — an alias or a differently-cased name is
    rejected; resolve those through :func:`canonical_language_id` first.

    Args:
        language_id: The candidate language id.

    Returns:
        *language_id*, verified to be a canonical language id.

    Raises:
        ValueError: If *language_id* is not a canonical language id.
    """
    return _checked_code_language_id(language_id)
